name: deploy
on:
    push:
        branches:
            - master
    workflow_dispatch:

env:
  FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
  FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
  FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
  FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
  FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
  FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
  FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 60
        steps:
            - name: checkout
              uses: actions/checkout@main

            - name: clear npm cache
              run: npm cache clean --force

            - name: setup volta
              uses: volta-cli/action@master

            - name: module install
              run: YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn

            - name: build client
              run: NODE_OPTIONS="--max-old-space-size=4096" yarn generate

            - name: deploy client
              uses: nogsantos/scp-deploy@master
              with:
                  src: ./.output/public/*
                  key: ${{ secrets.SSH_PRIVATEKEY }}
                  host: ${{ secrets.SSH_HOST }}
                  port: ${{ secrets.SSH_PORT }}
                  user: ${{ secrets.SSH_USERNAME }}
                  remote: ${{ secrets.SSH_REMOTE_CLIENT }}

            - name: Finalize deployment
              uses: appleboy/ssh-action@master
              with:
                  key: ${{ secrets.SSH_PRIVATEKEY }}
                  host: ${{ secrets.SSH_HOST }}
                  port: ${{ secrets.SSH_PORT }}
                  username: ${{ secrets.SSH_USERNAME }}
                  command_timeout: 64m
                  script: |
                      cd ${{ secrets.SSH_REMOTE_CLIENT }}
                      cd ../../
                      ~/.volta/bin/npx wrangler pages deploy dist --project-name ktak-dev
